[windmill]
name = "Windmill"
power.production = 30

[miner]
name = "Miner"
power.consumption = 5
conveyor_holes = [
  { direction = "outbound", translation = [16, 16, 10] },
]

[power_pole]
name = "Power Pole"
power.sockets = 4

[constructor]
name = "Constructor"
recipe.default_recipe = "iron_plates"
power.consumption = 15
conveyor_holes = [
  { direction = "inbound", translation = [-18, -12, 10] },
  { direction = "outbound", translation = [18, -12, 10] },
]

[smelter]
name = "Smelter"
recipe.default_recipe = "smelt_iron"
conveyor_holes = [
 { direction = "inbound", translation = [-28, -16, 10] },
 { direction = "outbound", translation = [28, -16, 10] },
]

[merger]
name = "Merger"
conveyor_holes = [
  { direction = "inbound", translation = [-18, -12, 10] },
  { direction = "inbound", translation = [0, -24, 10] },
  { direction = "inbound", translation = [0, 24, 10] },
  { direction = "outbound", translation = [18, -12, 10] },
]
